global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['my.previsioniweather.com:9090']

  - job_name: 'metrics_scraper'
    static_configs:
      - targets: ['metrics_scraper:9100']

